In [1]:
from darts.models import Prophet

champion = Prophet.load("../models/champion_prophet.pkl")

Support for PyTorch based likelihood models not available. To enable them, install "darts[torch]" or "darts[all]" (with pip); or "u8darts-torch" or "u8darts-all" (with conda).
Support for Torch based models not available. To enable them, install "darts[torch]" or "darts[all]" (with pip); or "u8darts-torch" or "u8darts-all" (with conda).
D:\data analytics\TimeSeries\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Importing plotly failed. Interactive plots will not work.
The StatsForecast module could not be imported. To enable support for the AutoARIMA, AutoETS and Croston models, please consider installing it.


In [2]:
forecast = champion.predict(90)

Hyperparameter tuning was performed with HyperOpt using the fixed evaluation split (train: 2013, test: Jan–Mar 2014) and consistent metrics (MAE, RMSE, sMAPE). All experiments were tracked with MLflow (file-based tracking). Among tuned candidates, Prophet achieved the lowest sMAPE (21.75%), outperforming tuned SARIMA (21.93%) and tuned Ridge regression (22.80%). Prophet was selected as the champion model and saved as ../models/champion_prophet.pkl for reuse in Week 4.

### Create Final Champion Comparison Table

In [3]:
import pandas as pd

summary = pd.DataFrame([
    {
        "model": "Ridge (tuned)",
        "primary_metric": "sMAPE",
        "smape": 22.79886316661221,
        "mae": 101.11775622556578,
        "rmse": 147.61966396544955
    },
    {
        "model": "SARIMA (tuned)",
        "primary_metric": "sMAPE",
        "smape": 21.93279760563738,
        "mae": None,   # optional: you can fill exact values if you want
        "rmse": None
    },
    {
        "model": "Prophet (tuned)",
        "primary_metric": "sMAPE",
        "smape": 21.746483761529063,
        "mae": None,
        "rmse": None
    }
])

summary = summary.sort_values("smape").reset_index(drop=True)
summary

,model,primary_metric,smape,mae,rmse
0,Prophet (tuned),sMAPE,21.746484,NaN,NaN
1,SARIMA (tuned),sMAPE,21.932798,NaN,NaN
2,Ridge (tuned),sMAPE,22.798863,101.117756,147.619664


* Hyperparameter tuning improved Prophet from ~21.93% sMAPE to 21.75%.
* SARIMA tuning produced marginal improvement (~21.93%).
* Ridge regression did not benefit significantly from regularization tuning.
* Prophet achieved the lowest sMAPE and was selected as the champion model.